import { createTheme, MantineProvider } from '@mantine/core';
import '@mantine/core/styles.css';
import { Rubik } from 'next/font/google';
import '../shared/styles/styles.css';

const theme = createTheme({
  headings: {
    sizes: {
      h1: {
        fontSize: '5rem',
        lineHeight: '6rem',
      },
      h2: {
        fontSize: '3.7rem',
        lineHeight: '4rem',
      },
    },
  },
});

const rubikSans = Rubik({
  variable: '--font-geist-sans',
  subsets: ['latin'],
  weight: '400',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${rubikSans.className} antialiased box-border m-0 p-0`}>
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
