import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import '../styles/styles.css';

const rubikSans = Rubik({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubikSans.className} antialiased box-border m-0 p-0`}
      >
        {children}
      </body>
    </html>
  );
}
